# 課題0628

そのまま課題ファイルで編集しないでください。課題ファイルを複製してから課題を回答してください。

## 課題１

- ```NumPy```を使って、最小二乗法で重回帰分析の係数を推定する関数を作成しよう。
- 与えられたデータで実装して動作を確認せよ。

In [77]:
import numpy as np

def get_PartialRegressionCoefficient(X, y):
    PRC = np.linalg.lstsq(X, y)
    return(PRC[0]) 


In [78]:
import numpy as np

def get_PartialRegressionCoefficient_2(X, y):
    a1 = np.dot(X.T, X)
    a1 = np.linalg.inv(a1)
    a2 = np.dot(X.T, y)
    PRC = np.dot(a1, a2)
    return(PRC) 

In [79]:
# このコードを実行し、データの読み込み
# もしsklearnがインストールされていない場合は、!pip install sklearnを実行してください
import numpy as np
from sklearn.datasets import load_iris

# Irisデータセットをロード
iris = load_iris()

X = np.delete(iris.data, 1, 1)# 説明変数のデータ
Y = iris.data[:, 1]  # 目的変数のデータ（がく片の幅）


In [80]:
get_PartialRegressionCoefficient(X, Y)

C:\Users\makot\AppData\Local\Temp/ipykernel_21052/1896501838.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  PRC = np.linalg.lstsq(X, y)


array([ 0.83778945, -0.66893846,  0.55610531])

In [62]:
# Yを従属変数、Xを独立変数として、線形回帰モデルを作成し、回帰係数を求める
get_PartialRegressionCoefficient_2(X, Y)

array([ 0.83778945, -0.66893846,  0.55610531])

## 課題2

以下の指示に従ってクラスを作成してください。

- クラスをインスタント化する際は二つ同じサイズの```ndarray```($v_1$と$v_2$)が渡されます
- クラスに$v_1$と$v_2$が同じサイズであるかどうかを確認するメソッドを実装しよう
- クラスに$v_1$が$v_2$に射影する結果を計算するメソッドを実装しよう
- クラスに$v_1$と$v_2$のコサイン類似度を計算するメソッドを実装しよう

In [68]:
class Vector:
    def __init__(self, v1, v2):
        self.v1 = v1
        self.v2 = v2

    def check_size(self):
        print(self.v1.size == self.v2.size)
    
    def proj(self):
        a1 = np.dot(self.v1, self.v2)
        a2 = np.dot(self.v2, self.v2)
        return np.dot((a1/a2), self.v2)
    
    def cossim(self):
        b1 = np.dot(self.v1, self.v2)
        b2 = np.linalg.norm(self.v1) * np.linalg.norm(self.v2)
        return b1/b2



In [76]:
# 確認
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

c = Vector(v1, v2)

print(c.check_size())
print(c.proj())
print(c.cossim())

True
None
[1.66233766 2.07792208 2.49350649]
0.9746318461970762
